sudo: required

services:
  - docker

before_install:

script:
  - docker-compose run --rm -e CI=true client sh -c "npm run test && npm run lint"

after_success:
  - docker build -t rzldev/multi-client:2.0 ./client
  - docker build -t rzldev/multi-worker:2.0 ./worker
  - docker build -t rzldev/multi-server:2.0 ./server
  - docker build -t rzldev/multi-nginx:2.0 ./nginx
  # Login to docker cli
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  # Take those images and push them to docker hub
  - docker push rzldev/multi-client:2.0
  - docker push rzldev/multi-worker:2.0
  - docker push rzldev/multi-server:2.0
  - docker push rzldev/multi-nginx:2.0

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-1-347246329864867"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
