---
name: Checks
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  prepare-to-deploy:
    name: Prepare to deploy
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test and Lint client app
        run: docker-compose run --rm -e CI=true client sh -c "npm run test && npm run lint"
      - name: Build client docker image
        run: docker build -t rzldevdoc/multi-client:2.0 ./client
      - name: Push client docker image
        run: docker push rzldevdoc/multi-client
      - name: Build worker docker image
        run: docker build -t rzldevdoc/multi-worker:2.0 ./worker
      - name: Push worker docker image
        run: docker push rzldevdoc/multi-worker
      - name: Build api docker image
        run: docker build -t rzldevdoc/multi-api:2.0 ./server
      - name: Push api docker image
        run: docker push rzldevdoc/multi-api
      - name: Build nginx docker image
        run: docker build -t rzldevdoc/multi-nginx:2.0 ./nginx
      - name: Push nginx docker image
        run: docker push rzldevdoc/multi-nginx
